meta_name: "Drive Guru"
meta_title: "Drive Guru - Drive confidently with the right instructor by your side"
meta_description: "DriveGuru is an app that connects aspiring learner drivers with reliable driving instructors across Mauritius. Whether you are a student or a teacher, you are bound to find the perfect match on DriveGuru!"
meta_image: "logo.png"
